Script started on 2017年03月17日 (週五) 23時23分10秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m whoami [K; pwd
pd2vm
/home/pd2vm
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git config -l
user.name=niwabis
user.email=dark19981023@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m exit

Script done on 2017年03月17日 (週五) 23時24分09秒
